### PR TITLE
bio-tbtools rename tbtools's  to bio-tbtools

### PR DESCRIPTION
**Pull request by Kiri2002**
## Involved packages

 - tbtools
 - bio-tbtools

## Involved issue

Rename to bio-tbtools to avoid conflicting with extra/tbtools for Thunder Bolt

Close #

## Details

- [x] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [x] Fix the Packages
  - [x] PKGBUILD
  - [x] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Comment by Kiri2002** [comment]
In this commit, it was renamed and added AUR package

**Comment by Kiri2002** [comment]
I have tested the renamed package, no conflict with extra/tbtools.
 extra/tbtools:
 ```
 tbtools /usr/
tbtools /usr/bin/
tbtools /usr/bin/tbadapters
tbtools /usr/bin/tbauth
tbtools /usr/bin/tbdump
tbtools /usr/bin/tbget
tbtools /usr/bin/tblist
tbtools /usr/bin/tbman
tbtools /usr/bin/tbmargin
tbtools /usr/bin/tbpd
tbtools /usr/bin/tbset
tbtools /usr/bin/tbtrace
tbtools /usr/share/
tbtools /usr/share/licenses/
tbtools /usr/share/licenses/tbtools/
tbtools /usr/share/licenses/tbtools/LICENSE
```

bio-tbtools:
```
bio-tbtools /usr/
bio-tbtools /usr/bin/
bio-tbtools /usr/bin/tbtools
bio-tbtools /usr/share/
bio-tbtools /usr/share/applications/
bio-tbtools /usr/share/applications/tbtools.desktop
bio-tbtools /usr/share/bio-tbtools/
bio-tbtools /usr/share/bio-tbtools/tbtools.jar
bio-tbtools /usr/share/icons/
bio-tbtools /usr/share/icons/hicolor/
bio-tbtools /usr/share/icons/hicolor/16x16/
bio-tbtools /usr/share/icons/hicolor/16x16/apps/
bio-tbtools /usr/share/icons/hicolor/16x16/apps/tbtools.png
bio-tbtools /usr/share/icons/hicolor/720x720/
bio-tbtools /usr/share/icons/hicolor/720x720/apps/
bio-tbtools /usr/share/icons/hicolor/720x720/apps/tbtools.png
bio-tbtools /usr/share/licenses/
bio-tbtools /usr/share/licenses/bio-tbtools/
bio-tbtools /usr/share/licenses/bio-tbtools/LICENSE
```

**Comment by starsareintherose** [comment]
Please solve the conflict firstly

**Comment by starsareintherose** [comment]
Please add BioArchLinuxBot as co-maintianer instead of lilac

**Comment by Kiri2002** [comment]
> Please solve the conflict firstly

Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

The conflict is caused by delete the tbtools folder. It need write acess maybe?



> Please add BioArchLinuxBot as co-maintianer instead of lilac

changed

**Comment by starsareintherose** [comment]
If can't solve conflict, it seems that it can't be merged

**Pull request closed without merging**
