### PR TITLE
SnpEff PKGBUILD rewritten to compile from source

### LINKED ISSUE #85: [MAINTAIN] java related packages polishment
**List of Pacakges**

<details>

- [x] aliview
- [x] artemis
- [x] bbmap
- [x] beast
- [x] beast2
- [x] canu
- [x] #101
- [x] emboss
- [x] fastqc
- [x] figtree
- [x] gatk
- [x] insight-toolkit
- [x] jane
- [x] libsbml
- [x] mcscanx
- [x] mesquite
- [x] morphoj
- [x] open-delta
- [x] phyde
- [x] phylip
- [x] pibuss
- [x] phylonet
- [x] picard
- [x] sequencematrix
- [x] spread3
- [x] spread
- [x] tempest
- [x] tracer
- [x] treemap
- [x] trimmomatic

 </details>

**Description**

These packages need to be checked the following points
- [x] use `java-runtime` and `java-enviroment` instead of jdk, jre, etc.
- [x] confirm the java version and limit the enviroment in PKGBUILD
- [x] check if they can be compiled from the source code [may be difficult, considering some software use quite low version java-enviroment]
- [x] check if PKGBUILD style can be auto updated

### PR DESCRIPTION
**Pull request by kbipinkumar**
## Involved packages

 - snpeff and snpsift

## Involved issue

Close #85 

## Details

- [x] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [x] Fix the Packages
  - [x] PKGBUILD
  - [x] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

## Additional Note

i have closed the previous pull request as it was too cumbersome to squash all commits. this version of PKGBUILD does compile from source successfully. i have also tested the resulting binaries for functionality and those seem to work as expected (similar to existing package in AUR repo). 

in line with AUR repo package i have also added binary wrappers for jar executables so that users can call up the jar files using `snpeff` and `snpsift` instead of typing the whole `java -jar '/usr/share/java/snpEff/snpEff.jar'` everytime they want to run the tool.

### CODE REVIEW

**Comment by hubutui** [comment]
Cool, could you update `lilac.yaml` to use LF line terminators?
Then you could:
```bash
git add lilac.yaml
git commit --amend
git push -f
```
without creating another commit.

**Comment by hubutui** [comment]
You change the line terminators according to this [link](https://stackoverflow.com/questions/2613800/how-to-convert-dos-windows-newline-crlf-to-unix-newline-lf). Or use some editor, like vs code.

**Comment by kbipinkumar** [comment]
> Cool, could you update `lilac.yaml` to use LF line terminators? Then you could:
> 
> ```shell
> git add lilac.yaml
> git commit --amend
> git push -f
> ```
> 
> without creating another commit.

i am using vscode. anyways i have double checked for using LF line terminators. please check now

**Comment by hubutui** [comment]
install the `MIT` license file to `/usr/share/licenses/$pkgname`, since `MIT` is not listed in [licenses](https://archlinux.org/packages/core/any/licenses/).

**Comment by kbipinkumar** [comment]
you mean copying license file from source folder like this

```
install -Dm644 ${srcdir}/$_pkgname-$pkgver/LICENSE.md "${pkgdir}"/usr/share/licenses/$pkgname/LICENSE
```
should be changed to 

```
install -Dm644 ${srcdir}/$_pkgname-$pkgver/LICENSE.md "${pkgdir}"/usr/share/licenses/$pkgname/MIT
```
?

**Pull request merged**
