### PR TITLE
veusz: fork veusz from AUR

### PR DESCRIPTION
**Pull request by Kiri2002**
veusz is a SCI-plot software compare to origin

## Involved packages

 - Packages_Name

## Involved issue

Close #

## Details

- [ ] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [ ] Fix the Packages
  - [ ] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Comment by starsareintherose** [comment]
please alias to python

**Comment by starsareintherose** [comment]
lilac.yaml is wrong, please see other github source based lilac.yaml

**Comment by Kiri2002** [comment]
> please alias to python

what your mean, idg( i don't get)

**Comment by Kiri2002** [comment]
> lilac.yaml is wrong, please see other github source based lilac.yaml

Fixed

**Comment by Kiri2002** [comment]
> please alias to python

i got it, done
- alias: python

**Pull request merged**
