### PR TITLE
glimmerhmm: add glimmerhmm

### PR DESCRIPTION
**Pull request by Kiri2002**
glimmerhmm is a new gene finder based on a Generalized Hidden Markov Model (GHMM).

## Involved packages

 - Packages_Name

## Involved issue

Close #

## Details

- [ ] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [ ] Fix the Packages
  - [ ] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Comment by Kiri2002** [comment]
notice:
in PKGBUILD i write this way:
```
# source=(${pkgname}-${pkgver}.tar.gz::${url}/dl/${_pkgname}-${pkgver}.tar.gz)
# sha256sums=('43e321792b9f49a3d78154cbe8ddd1fb747774dccb9e5c62fbcc37c6d0650727')

build() {
  wget -O ${pkgname}-${pkgver}.tar.gz ${url}/dl/${_pkgname}-${pkgver}.tar.gz
  tar -xzf ${srcdir}/${pkgname}-${pkgver}.tar.gz
  cd "${srcdir}/${_pkgname}/sources" || exit
  make
}
```
beacuse the service's curl gets wrong: 
```curl: (35) OpenSSL/3.1.1: error:0A000172:SSL routines::wrong signature type```
I think this is bad beacuse the service's config, only set-lower-ssl-security-level could fix, so i turn to wget

**Comment by starsareintherose** [comment]
> notice: in PKGBUILD i write this way:
> 
> ```
> # source=(${pkgname}-${pkgver}.tar.gz::${url}/dl/${_pkgname}-${pkgver}.tar.gz)
> # sha256sums=('43e321792b9f49a3d78154cbe8ddd1fb747774dccb9e5c62fbcc37c6d0650727')
> 
> build() {
>   wget -O ${pkgname}-${pkgver}.tar.gz ${url}/dl/${_pkgname}-${pkgver}.tar.gz
>   tar -xzf ${srcdir}/${pkgname}-${pkgver}.tar.gz
>   cd "${srcdir}/${_pkgname}/sources" || exit
>   make
> }
> ```
> 
> beacuse the service's curl gets wrong: `curl: (35) OpenSSL/3.1.1: error:0A000172:SSL routines::wrong signature type` I think this is bad beacuse the service's config, only set-lower-ssl-security-level could fix, so i turn to wget

The reason is same like bedtools, use HTTP instead of https, polish it

**Comment by starsareintherose** [comment]
For the PR title, you should follow the standard of commit `pkgname: what you did`

**Comment by starsareintherose** [comment]
now if you adjust the source from `https` to `http`, test it via `devtools` successfully, then this pkg can be merged

**Comment by starsareintherose** [comment]
what are you doing?

**Comment by starsareintherose** [comment]
it's not okay

**Comment by Kiri2002** [comment]
> it's not okay

where? and my laptop only 9% charge, soon die

**Comment by starsareintherose** [comment]
you shouldn't merge it by your own, you haven't did what I requested, please understand what I said! plz! 

image
image

Please reply them one by one and polish your code

**Pull request merged**
