### PR TITLE
glimmerhmm: add glimmeerhmm

### PR DESCRIPTION
**Pull request by Kiri2002**
## Involved packages

 - Packages_Name

## Involved issue

Close #

## Details

- [x] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [x] Provide New Package
- [ ] Fix the Packages
  - [x] PKGBUILD
  - [x] lilac.yaml
  - [ ] lilac.py
- [x] Would like to continue to work with us

### CODE REVIEW

**Comment by Kiri2002** [comment]
@starsareintherose I'm coming back

**Comment by starsareintherose** [comment]
Again, have you tested it under devtools? Could you fullfill the pr template information?

**Comment by Kiri2002** [comment]
> Again, have you tested it under devtools? Could you fullfill the pr template information?
i thinks it is passed, only two warning in  extra-x86_64-build 
```
==> WARNING: Skipping all source file integrity checks.
error: target not found: glimmerhmm
==> WARNING: Skipped checkpkg due to missing repo packages
```
looks nice?

**Comment by kbipinkumar** [comment]
using variables url=() function like this `url="https://ccb.jhu.edu/software/${pkgname}"` doesn't seem to be a good practice. its okay for source=() array

also the package folder is in the wrong location. it needs to be in Packages/Bioarchlinux and not Packages/

**Pull request merged**
