### PR TITLE
Adding cutadapt and dependencies

### LINKED ISSUE #108: Add cutadapt to repository
Add cutadapt along with dependencies

### PR DESCRIPTION
**Pull request by kbipinkumar**
## Involved packages

 - cutadapt
 - python-xopen
 - python-dnaio
 - python-isal

## Involved issue

Close #108 

## Details

- [X] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [X] Provide New Package
- [X] Fix the Packages
  - [X] PKGBUILD
  - [X] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Comment by hubutui** [comment]
It seems `python-isal` includes a copy of `isa-l` source in the source tarball. And `/usr/lib/python3.10/site-packages/isal/_isal.cpython-310-x86_64-linux-gnu.so` is statically linked. So `python-isal` does not depends on `isa-l`.

**Comment by kbipinkumar** [comment]
> You could use `pypi` as [nvchecker doc](https://nvchecker.readthedocs.io/en/latest/usage.html#check-pypi) describes. refere to this [example](https://github.com/archlinuxcn/repo/blob/6c67a3e4228f4c7ea8ac44030f057f839989b3d5/archlinuxcn/python-jsmin/lilac.yaml#L9-L10). Add also `python` alias, which will automatically rebuild when python upgrade.

i was using this [lilac.yaml](https://github.com/BioArchLinux/Packages/blob/master/BioArchLinux/python-dendropy/lilac.yaml) as template. anyways i will make modifications as suggested.

**Comment by hubutui** [comment]
You could use `extra-x86_64-build` to build these pkgs in a clean chroot, see also [arch wiki](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot). If your pkg depends on pkg from bioarchlinux, you could use `bioarchlinux-x86_64-build`, which is available in `devtools-bio`.
The pkg checking outputs some useful informations, such as license is not listed in `licenses` pkg, so you need to install the license file manually.

**Comment by hubutui** [comment]
You miss maintainer tag in all `PKGBUILD`, add something like this to the head of the `PKGBUILD`:
```
# Maintainer: yourname <your email>
```

**Comment by kbipinkumar** [comment]
> You could use `pypi` as [nvchecker doc](https://nvchecker.readthedocs.io/en/latest/usage.html#check-pypi) describes. refere to this [example](https://github.com/archlinuxcn/repo/blob/6c67a3e4228f4c7ea8ac44030f057f839989b3d5/archlinuxcn/python-jsmin/lilac.yaml#L9-L10). Add also `python` alias, which will automatically rebuild when python upgrade.

- `lilac.yaml` is now using pypi as update source as per docs
- All the PKGBUILDs builds packages successfully in chroot
- maintainer info has been added
-  redundant dependencies on `isal` for `python-xopen` has been removed.

**Comment by kbipinkumar** [comment]
@hubutui can this be merged?

**Comment by kbipinkumar** [comment]
@hubutui can this be merged? i know i have merge rights. but as a newcomer i would appreciate extra set of eyes

**Comment by hubutui** [comment]
@kbipinkumar It seems that you just miss my comment. `python-xopen` should be `arch=('any')` as ` No ELF files and not an "any" package`. You should take a look at the message that `bioarchlinux-x86_64-build` command output.

**Comment by kbipinkumar** [comment]
> @kbipinkumar It seems that you just miss my comment. `python-xopen` should be `arch=('any')` as ` No ELF files and not an "any" package`. You should take a look at the message that `bioarchlinux-x86_64-build` command output. Make sure you have [namcap](https://archlinux.org/packages/extra/any/namcap/) installed. See also [namcap](https://wiki.archlinux.org/title/Namcap) in arch wiki.

PKGBUILDS updated per c3a88b1 commit

**Comment by hubutui** [comment]
1. `_name` and `_module` are the same. You only need one. You could follow the [arch wiki](https://wiki.archlinux.org/title/Python_package_guidelines#Source) to set `source` array.
2. it seems _pkgver is never used, why did you add this?
again, you just miss the comment on every file.

**Comment by kbipinkumar** [comment]
> 1. `_name` and `_module` are the same. You only need one. You could follow the [arch wiki](https://wiki.archlinux.org/title/Python_package_guidelines#Source) to set `source` array.
> 2. it seems _pkgver is never used, why did you add this?
>    again, you just miss the comment on every file.
> 
> image

oops i never got notifications for this. anyways i will make the changes asap.

**Comment by hubutui** [comment]
It seems that you delete the sources of `cutadapt/PKGBUILD` by mistake?

**Comment by kbipinkumar** [comment]
> It seems that you delete the sources of `cutadapt/PKGBUILD` by mistake?

sorry, it should be added back in latest commit f1405de

**Pull request merged**
