### PR TITLE
seqan3: build from source tarball

### PR DESCRIPTION
**Pull request by kbipinkumar**
## Involved packages

 - seqan3

## Details

- [x] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [x] Fix the Packages
  - [x] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

## Additional Note
the modified PKGBUILD builds seqan3 from sources by following build instructions from upstream.

### CODE REVIEW

**Comment by starsareintherose** [comment]
Prepare should be like
```
prepare(){
  cd ${srcdir}/xxxxxxx
  git submodule update --init --recursive
}
```

**Comment by kbipinkumar** [comment]
> Prepare should be like
> 
> ```
> prepare(){
>   cd ${srcdir}/xxxxxxx
>   git submodule update --init --recursive
> }
> ```

using this produces following error

```bash
==> Starting prepare()...
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by starsareintherose** [comment]
> > Prepare should be like
> > ```
> > prepare(){
> >   cd ${srcdir}/xxxxxxx
> >   git submodule update --init --recursive
> > }
> > ```
> 
> using this produces following error
> 
> ```shell
> ==> Starting prepare()...
> fatal: not a git repository (or any of the parent directories): .git
> ```

Yeah, you should add git to makedepends, then source should git+https://xxxxx.git#tag=v${pkgver}

then you should be careful, `cd $srcdir/$pkgname-$pkgver`  should be replaced with `cd $srcdir/$pkgname`, then this issue will be resolved

**Comment by kbipinkumar** [comment]
> > > Prepare should be like
> > > ```
> > > prepare(){
> > >   cd ${srcdir}/xxxxxxx
> > >   git submodule update --init --recursive
> > > }
> > > ```
> > 
> > 
> > using this produces following error
> > ```shell
> > ==> Starting prepare()...
> > fatal: not a git repository (or any of the parent directories): .git
> > ```
> 
> Yeah, you should add git to makedepends, then source should be `git+https://xxxxx.git#tag=v${pkgver}`, you can refer raxml-ng or iqtree, they are great example for this type pkg
> 
> then you should be careful, `cd $srcdir/$pkgname-$pkgver` should be replaced with `cd $srcdir/$pkgname`, then this issue will be resolved

modified PKGBUILD  as below

```
source=(git+https://github.com/seqan/seqan3.git#tag=${pkgver})
sha256sums=('SKIP')

prepare (){
    # cd  ${pkgname}-${pkgver}
    cd ${srcdir}/${pkgname}
    git submodule update --init --recursive https://github.com/xxsds/sdsl-lite.git


}
```

and gives following error now

```bash
==> Extracting sources...
  -> Creating working copy of seqan3 git repo...
Cloning into 'seqan3'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
error: pathspec 'https://github.com/xxsds/sdsl-lite.git' did not match any file(s) known to git
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by starsareintherose** [comment]
> git submodule update --init --recursive

What I write is 
```
git submodule update --init --recursive
```

You have extra git link

**Pull request merged**
