### PR TITLE
r-bff: fix build r-bff pkg

### PR DESCRIPTION
**Pull request by shun2wang**
## Involved packages

 - r-bff

## Involved issue

Close #

## Details

- [ ] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [ ] Fix the Packages
  - [ ] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Comment by starsareintherose** [comment]
Please don't create any new branch for this repo

**Comment by starsareintherose** [comment]
It will cause problems of CI

**Comment by shun2wang** [comment]
> Please don't create any new branch for this repo

Any branch on my personal fork is also not allowed?

**Comment by shun2wang** [comment]
Then I deleted my branch.

**Comment by kbipinkumar** [comment]
> Please don't create any new branch for this repo

maybe we should add a howto section in the rep as well

**Comment by shun2wang** [comment]
I think I did following above step in my local. The only difference is that I forcefully rebased my branch onto `master:head` and used `push -f`.

**Comment by shun2wang** [comment]
Sorry if I screwed something up, we can revert the commit.😁🍻

**Comment by starsareintherose** [comment]
> > Please don't create any new branch for this repo
> 
> maybe we should add a howto section in the repo as well.
> 
> i have written a draft HOWTO [here](https://gist.github.com/kbipinkumar/aed64c09370f05f99207bfa5de846955) if its okay we can work on adding it to repo

Great, please give a pr

**Comment by starsareintherose** [comment]
> Sorry if I screwed something up, we can revert the commit.😁🍻

Don't worry

**Pull request merged**
