### PR TITLE
tbtools: fix entry name

### PR DESCRIPTION
**Pull request by Kiri2002**
new entry name "tbtools" may be better, especially works well in kde/gnome's search bar

## Involved packages

 - Packages_Name

## Involved issue

Close #

## Details

- [ ] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [x] Fix the Packages
  - [x] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Review by starsareintherose — COMMENTED** [review]
Why tbtools is known as tbtools, you want it use complex name for users?

**Comment by Kiri2002** [comment]
> Why tbtools is known as tbtools, you want it use complex name for users?

Sorry I used made this mistake and this pr should fix it.

**Comment by starsareintherose** [comment]
I can't understand why you said, you may not get what I said

**Comment by Kiri2002** [comment]
Yes, TBtools is known for TBtools.
Where aim to change is: --name="Tool Box for biologistists" to "tbtools", so that when search for tbtools in KDE/gnome, it can be show. But if it is ""Tool Box for biologistists", it will now shown.
And i don't change the description， only change the desktop entry's name to tbtools.

**Pull request merged**
