### PR TITLE
Incorporate AUR package chimerax

### PR DESCRIPTION
**Pull request by kashyapchhatbar**
## Involved packages

 - chimerax

## Involved issue

Incorporate AUR package [chimerax](https://aur.archlinux.org/packages/chimerax) in BioArchLinux repo

## Details

- [x] Tested in the local machine (largest 32G RAM) and it is passed without any issue
- [x] Provide New Package
- [x] Would like to continue to work with us

## Additional Note

This package is adapted from the AUR package [chimerax](https://aur.archlinux.org/packages/chimerax) and the contributions are mentioned in the PKGBUILD

### CODE REVIEW

**Comment by hubutui** [comment]
Hmm, could we use a source URL and let the `devtools` download automatically? I cannot visit https://www.cgl.ucsf.edu/chimerax/,  so I'm not sure how this work. Is there a valid and pattern URL for the binary tarball?

**Comment by hubutui** [comment]
Ok, it seems one must manually accept the license before downloading the binary tarball.
I also found that this pkg is open source, and the source code is available at https://github.com/RBVI/ChimeraX. Building from the source is preferred when possible.

**Comment by kbipinkumar** [comment]
source code is available at [github ]( https://github.com/RBVI/ChimeraX) seems to have `pyproject.toml` [file](https://github.com/RBVI/ChimeraX/blob/develop/pyproject.toml) included. so, it's worth attempting to package from source using instructions from [Python package guidelines](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)).

```
makedepends=(python-build python-installer python-wheel)

build() {
    cd "$_name-$pkgver"
    python -m build --wheel --no-isolation
}

package() {
    cd "$_name-$pkgver"
    python -m installer --destdir="$pkgdir" dist/*.whl
}
```

**Comment by hubutui** [comment]
@kbipinkumar  No, I don't think it will work. The method you mentioned only installs the python part. There are C++ sources that need to be compiled. It seems that this pkg also builds a bundled python 3.9, just like [3dslicer](https://github.com/Slicer/Slicer), which makes it complicated to build it from the source in other Linux distributions.

**Comment by hubutui** [comment]
dep `libffi6` is not available in official repo or bioarchlinux repo, you need to add it to bioarchlinux too. Or you could check if this pkg works with `libffi`.

**Comment by kashyapchhatbar** [comment]
@hubutui and @kbipinkumar I agree with your points and reservations about adding this package to the repository. As mentioned, ChimeraX is quite tricky to build if we were to follow all packaging guidelines. I will leave it up to you guys on how to proceed.

**Comment by hubutui** [comment]
@kashyapchhatbar I'm ok if you want to add this pkg. We need some modifications:
1. information for user should be move to `post_install()`. You could check [cuda pkg](https://github.com/archlinux/svntogit-community/blob/packages/cuda/trunk/cuda.install) for example. All pkg added here is built by a robot, and the user installs it by `pacman`, not build it from `PKGBUILD`.
2. `lilac.yaml` is missing for the robot to automatically update when chimerax upgrade.
3. `libffi6` is not available here, you could either add it here too, or check if this pkg works with `libffi` by creating a soft link to the soname file.

**Comment by starsareintherose** [comment]
Another thing I am intereste why source only contain two local files

**Comment by kbipinkumar** [comment]
tried my luck building from git source using `make install` as suggested in documentation. process exited with following error

```bash
filters/video/resize.c: In function ‘pick_closest_supported_csp’:
filters/video/resize.c:212:30: error: ‘AVComponentDescriptor’ has no member named ‘depth_minus1’
  212 |         if( pix_desc->comp[i].depth_minus1 >= 8 )
      |                              ^
make[4]: *** [<builtin>: filters/video/resize.o] Error 1
```

**Comment by hubutui** [comment]
> tried my luck building from git source using `make install` as suggested in documentation. process exited with following error
> 
> ```shell
> filters/video/resize.c: In function ‘pick_closest_supported_csp’:
> filters/video/resize.c:212:30: error: ‘AVComponentDescriptor’ has no member named ‘depth_minus1’
>   212 |         if( pix_desc->comp[i].depth_minus1 >= 8 )
>       |                              ^
> make[4]: *** [<builtin>: filters/video/resize.o] Error 1
> ```

It seems related to ffmpeg. Maybe it depends on ffmpeg4.4, not ffmpeg 5.

**Comment by kbipinkumar** [comment]
> > tried my luck building from git source using `make install` as suggested in documentation. process exited with following error
> > ```shell
> > filters/video/resize.c: In function ‘pick_closest_supported_csp’:
> > filters/video/resize.c:212:30: error: ‘AVComponentDescriptor’ has no member named ‘depth_minus1’
> >   212 |         if( pix_desc->comp[i].depth_minus1 >= 8 )
> >       |                              ^
> > make[4]: *** [<builtin>: filters/video/resize.o] Error 1
> > ```
> 
> It seems related to ffmpeg. Maybe it depends on ffmpeg4.4, not ffmpeg 5.

according to [`makefile'](https://github.com/RBVI/ChimeraX/blob/2bd0f8b9692fad6fab08f973acf572859e1dfba0/prereqs/ffmpeg/Makefile) its FFMPEG_VERSION = 3.2.4

**Comment by hubutui** [comment]
@kashyapchhatbar maybe you could try another ffmpeg version. I'm not sure if it works.

**Comment by kashyapchhatbar** [comment]
Thanks for giving it a short @kbipinkumar but the guidelines from the ChimeraX developers recommends using production releases. I will implement the recommended changes and use the [compiled package](https://www.rbvi.ucsf.edu/chimerax/download.html#release).

**Comment by starsareintherose** [comment]
Yeah,  you can, when you finish this PR, I will invite you as a member of our team, you can add this to the todo list, one day, we may find solution to polish it

**Comment by kbipinkumar** [comment]
> Yeah, you can, when you finish this PR, I will invite you as a member of our team, you can add this to the todo list, one day, we may find solution to polish it

i wouldn't be that hopeful. according to their [build page](https://www.cgl.ucsf.edu/chimerax/docs/devel/building.html) the most recent version commonly used distros are ubuntu 20 series and centos 8.

**Comment by starsareintherose** [comment]
Thanks for your interest again. This pr will be closed as there is no progress near almost half year. You are still weclomed to submit new pr to our repo. Maybe start at a simpler one.
Best regards
Guoyi

**Pull request closed without merging**
