### PR TITLE
add dependencies for jasp-desktop

### PR DESCRIPTION
**Pull request by sukanka**
## Involved packages

 - Packages_Name

## Involved issue

Close #

## Details

- [x] Provide New Package
- [ ] Fix the Packages
  - [ ] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [x] Would like to continue to work with us

### CODE REVIEW

**Comment by starsareintherose** [comment]
please check the system requirements, BayesTools require jags

**Comment by starsareintherose** [comment]
bayesplot requires pandoc and so on

**Comment by starsareintherose** [comment]
RoBMA, runjags needs jags, rstanarm needs pandoc

**Comment by sukanka** [comment]
> please check the system requirements, BayesTools require jags

I have checked all the system requirements. 
BTW, they are commented out in PKGBUILD :rofl: , but I didn't aware of that until I manually checked most of the packages.

**Comment by starsareintherose** [comment]
please notice there is no package in our repo and arch repo called [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc), and for package added jags, your should change their lilac.yaml because it is not provided by arch repo

**Pull request merged**
