### PR TITLE
updated PKGBUILD for Augustus

### LINKED ISSUE #87: [REQUEST] add AUGUSTUS gene prediction tool
**Information**
 - Package Name: Augustus
 - Can it directly run on Linux: yes
 - Can it run on the wine: no
 -  Website: https://github.com/Gaius-Augustus/Augustus
 - Download URL: https://github.com/Gaius-Augustus/Augustus/releases
 - Package description: AUGUSTUS is a gene prediction tool for eukaryotic genomes
 - DOI: 10.1093/nar/gki458
 

**Popularity**
 - Number of citations from WOS per year: 41.78
 - Any other reason: this package is mandatory for Braker2 pipeline used for automatic eukaryotic genome annotation
 
 the package is available in aur and its PKGBUILD can adapted. 
 Note: there is an aur PKGBUILD available. however the build process errors out not finding bamtools although i have installed bamtools from bioarchlinux repository

### PR DESCRIPTION
**Pull request by kbipinkumar**
## Involved packages

 - Augustus

## Involved issue

Close #87 

## Details

- [X] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [X] Provide New Package
- [ ] Fix the Packages
  - [X] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Comment by starsareintherose** [comment]
Why install at /opt ? It should be under /usr, /opt is the optional file for one pkg

**Comment by sukanka** [comment]
> /opt is the optional file for one pkg

see https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#optAddonApplicationSoftwarePackages

**Comment by starsareintherose** [comment]
It seems that this pkg is not so complex, like pleroma-bin or cuda, it should under /usr/share/august

**Comment by sukanka** [comment]
> It seems that this pkg is not so complex, like pleroma-bin or cuda, it should under /usr/share/august

This pkg's arch is not `any`. So if non-executables are put into `/usr/share`, it should be tested first that this pkg still works.

**Comment by starsareintherose** [comment]
okay, you can test

**Comment by sukanka** [comment]
You do not need to to keep up with the master branch as long as there is no conflicts and the pr can be merged automatically.

**Comment by hubutui** [comment]
It would be better to git rebase and make this pr contains only one commit.

**Pull request merged**
