### PR TITLE
r-jaspsurvival: fix dependencies

### PR DESCRIPTION
**Pull request by shun2wang**
## Involved packages

 - r-jaspsurvival

## Involved issue

Close #

## Details

- [ ] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [x] Provide New Package
- [ ] Fix the Packages
  - [x] PKGBUILD
  - [x] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

### CODE REVIEW

**Comment by shun2wang** [comment]
not sure if I should add `r-survival` but seems it was fine with other pkgs.

**Comment by starsareintherose** [comment]
@sukanka @hubutui  I don't know how to answer this question

**Comment by hubutui** [comment]
这个一般依赖于包作者的说明，他写了就应该加进去。如果有测试的话，可以跑测试脚本，看报错。没什么特殊的方法。

**Comment by sukanka** [comment]
> 有没有一个文档或者指导，例如什么情况下我应该添加某个R包作为依赖项，因为我发现一些没有`r-xxx`的包工作的也很好。例如本案例中 `r-survival` 似乎已经以某种方式存在？

Just follow [R package guidelines](https://wiki.archlinux.org/title/R_package_guidelines). 
Some packages can work fine with missing dependency `r-xxx` as it may be included as an indirect dependency.
(e.g. A depends on B and C, but B also depends on C, so  if you declare that A only depends on B, it  still works)

**Pull request merged**
